### ISSUE TITLE
Current samples Vs OpenIdConnect.Server/samples

### ISSUE THREAD

**Issue by BrainCrumbz** [aspnet-contrib/AspNet.Security.OpenIdConnect.Samples#12]
How do samples in this current project compare to those found in [OpenIdConnect.Server/samples](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/tree/dev/samples)?

At least for the `Mvc` one, which is the one to follow?

Thank you

**Comment by kevinchalet** [comment]
The samples on the main repository always target the latest ASP.NET Core/aspnet-contrib bits (RC3 for the dev branch, RC2 for the release one) while this repository targets the latest stable release (RC1).

**Comment by BrainCrumbz** [comment]
Would it make sense to unify all of them under this Samples project, maybe split into a `Stable` and a `Dev`/`Latest`/`Unstable` subdirectories?

**Comment by kevinchalet** [comment]
> Would it make sense to unify all of them under this Samples project, maybe split into a Stable and a Dev/Latest/Unstable subdirectories?

It would make my work more painful, since I use the samples to ensure we don't break interoperability with the MSFT OIDC client when implementing new features.

**Comment by BrainCrumbz** [comment]
I see. I think we can throw two more PRs to the table, one for each project, commenting on those differences

**Comment by kevinchalet** [comment]
Thanks for your contribution :clap: 

Done: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples/commit/71ca6995d8641a7912463147a8cc0f45a6dbdd44.

**Comment by BrainCrumbz** [comment]
Great. As mentioned, probably we'll submit two small PRs soon with those differences.
