### ISSUE TITLE
signalr authorize atrribute example?

### ISSUE THREAD

**Issue by Jacknq** [aspnet-contrib/AspNet.Security.OpenIdConnect.Samples#19]
Could you provide example with hub class and authorize attribute? 
Interesting would be also changing the token expiration time etc.

**Comment by kevinchalet** [comment]
SignalR for ASP.NET Core is still a work in progress. No new sample will be added until it's released.

**Comment by Jacknq** [comment]
what relese you mean?  
now we re at 1.1
1.2 	Q2 2017
or what release are you waiting for so that we could start using this stuff meantime??

**Comment by kevinchalet** [comment]
SignalR for ASP.NET Core will ship with 1.2 (actually named 2.0).

@davidfowl do you confirm? :smile:
