### ISSUE TITLE
Question about the UseWhen extension method

### ISSUE THREAD

**Issue by atrauzzi** [aspnet-contrib/AspNet.Security.OpenIdConnect.Samples#7]
I've actually enjoyed similar functionality to the [`UseWhen` extension method](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples/blob/master/samples/Mvc/Mvc.Server/Extensions/AppBuilderExtensions.cs#L17) in other frameworks and languages, but I'm wondering...

Does the way it's implemented mean that you're rebuilding an entire new application pipeline for every request?  Is there any risk of this being inefficient?

**Comment by kevinchalet** [comment]
> Does the way it's implemented mean that you're rebuilding an entire new application pipeline for every request? Is there any risk of this being inefficient?

Actually, the branched pipeline is only built at startup time, thanks to the special `Use` overload that takes a `Func<RequestDelegate, RequestDelegate>`. The only part which is executed per-request is the request delegate itself:

``` csharp
return context => {
    if (condition(context)) {
        return branch(context);
    }

    return next(context);
};
```

**Comment by atrauzzi** [comment]
I love it.  Thanks! :)

**Comment by atrauzzi** [comment]
@PinpointTownes I was just going through the docs.asp.net and noticed the `Map` method.  Any differences between that and what you've made?

**Comment by kevinchalet** [comment]
https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/137#issuecomment-141702228

**Comment by atrauzzi** [comment]
Ahh, I see.  So if I used `MapWhen` vs `UseWhen`, I'd have to create two completely separate pipelines?  So `UseWhen` is good if you want to DRY out the setup of pipelines?

**Comment by kevinchalet** [comment]
Yep.
